### ISSUE TITLE
Not proper JSON error

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/views_calc#1]
@hosef I get this error when installing on a fresh site with the latest release:

> The configuration file "views_calc.settings" is not properly formatted JSON. Contents: <pre>{ &quot;_config_name&quot;: &quot;views_calc.settings&quot;, &quot;operators&quot;: &quot;+ - * / ( ) , &#039; CONCAT MIN MAX ROUND NOW()&quot; } </pre>

I just realized that the latest release doesn't include your bug fix. Would you be able to create a new release? Thanks.

**Comment by LucianoGit-x6zeta** [comment]
I just deleted the 'config' folder and the 'views_calc.settings.json' file from the 'view calc' folder in the 'modules' folder and it worked for me. Forgive me for my bad English

**Comment by hosef** [comment]
I created a new release, so this should hopefully be fixed now.
